export default {
    "arrow": 0,         // godot.CURSOR_ARROW,
    "ibeam": 1,         // godot.CURSOR_IBEAM,
    "pointing hand": 2, // godot.CURSOR_POINTING_HAND,
    "cross": 3,         // godot.CURSOR_CROSS,
    "wait": 4,          // godot.CURSOR_WAIT,
    "busy": 5,          // godot.CURSOR_BUSY,
    "drag": 6,          // godot.CURSOR_DRAG,
    "can drop": 7,      // godot.CURSOR_CAN_DROP,
    "forbidden": 8,     // godot.CURSOR_FORBIDDEN,
    "vertical resize": 9, // godot.CURSOR_VSIZE,
    "horizontal resize": 10, // godot.CURSOR_HSIZE,
    "main diagonal resize": 11, // godot.CURSOR_BDIAGSIZE,
    "secondary diagonal resize": 12, // godot.CURSOR_FDIAGSIZE,
    "move": 13,         // godot.CURSOR_MOVE,
    "vertical split": 14, // godot.CURSOR_VSPLIT,
    "horizontal split": 15, // godot.CURSOR_HSPLIT,
    "help": 16,         // godot.CURSOR_HELP,
}